### ISSUE TITLE
rtichoke not working with Emacs Shell (eshell)

### ISSUE THREAD

**Issue by dickoa** [randy3k/rtichoke#43]
Hi,

Thanks again for this great REPL, I always wanted to have something a la `IPython`.
I have an issue with Emacs shell (`eshell`), I can use `IPython` in `eshell` but not `rtichoke` (see screenshot).
Find below the error message

```bash
Error in options(width = 0L) : 
  invalid 'width' parameter, allowed 10...10000
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.6/site-packages/rtichoke/callbacks.py", line 17, in _read_console
    text = get_text(p.decode(ENCODING), add_history)
  File "/usr/lib/python3.6/site-packages/rtichoke/rtichokeapp.py", line 162, in result_from_prompt
    self.app_initialize(mp)
  File "/usr/lib/python3.6/site-packages/rtichoke/rtichokeapp.py", line 116, in app_initialize
    interface.set_option("width", mp.app.output.get_size().columns)
  File "/usr/lib/python3.6/site-packages/rtichoke/interface.py", line 138, in set_option
    rcall(api.mk_symbol("options"), **kwargs)
  File "/usr/lib/python3.6/site-packages/rtichoke/interface.py", line 83, in rcall
    raise RuntimeError("R eval error.")
RuntimeError: R eval error.
```
I use `Python` 3.6.4 and the following `R` version on Linux (4.15.7-1 Kernel on Arch Linux)

```r
R.version
               _                                          
platform       x86_64-pc-linux-gnu                        
arch           x86_64                                     
os             linux-gnu                                  
system         x86_64, linux-gnu                          
status         Patched                                    
major          3                                          
minor          4.3                                        
year           2018                                       
month          03                                         
day            01                                         
svn rev        74341                                      
language       R                                          
version.string R version 3.4.3 Patched (2018-03-01 r74341)
nickname       Kite-Eating Tree 
```

![rtichoke_eshell](https://user-images.githubusercontent.com/500140/37092053-3a9f9726-2202-11e8-9840-f66be3581669.png)

**Comment by randy3k** [comment]
I got a different error than yours
```
~ $ M-x eshell
~ $ rtichoke
Traceback (most recent call last):
  File "/Users/Randy/miniconda3/bin/rtichoke", line 11, in <module>
    load_entry_point('rtichoke==0.1.2', 'console_scripts', 'rtichoke')()
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/__init__.p\
y", line 105, in main
    RtichokeApplication(r_home).run(options)
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/rtichokeap\
p.py", line 157, in run
    mp = create_modal_prompt(options, history_file=".rtichoke_history", inputho\
ok=self.get_inputhook())
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/modalpromp\
t.py", line 328, in create_modal_prompt
    inputhook=inputhook
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/modalpromp\
t.py", line 90, in __init__
    self.input = input or CustomVt100Input(sys.stdin)
  File "/Users/Randy/miniconda3/lib/python3.5/site-packages/rtichoke/deps/promp\
t_toolkit/input/vt100.py", line 26, in __init__
    assert stdin.isatty()
AssertionError
```
It seems that emacs shell is not run on a tty? (I am not an emacs user, not sure about it)


Anyway, your error is because the terminal width cannot be determined and 0 is returned. e7a6d89 should have fixed it. Try installing the development version and see if it fixes your issue.

**Comment by dickoa** [comment]
Thanks a lot, it fixed the error, the only problem I have right now is that the R prompt disappeared (see screenshot). It's usable and thanks again for the quick fix.

![rtichoke_eshell](https://user-images.githubusercontent.com/500140/37108159-32bb1572-222e-11e8-8363-a7786ac2775c.png)

**Comment by randy3k** [comment]
It seems emacs shell doesn't support colored prompt? Try changing the `prompt` settings at
https://github.com/randy3k/rtichoke#settings
