### ISSUE TITLE
SystemError when loading the R package rPython

### ISSUE THREAD

**Issue by swt30** [randy3k/rtichoke#55]
```
r$> library(rPython)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/lib/python3.6/site-packages/rtichoke/callbacks.py", line 95, in write_console_ex
    buf = rconsole2str(buf)
  File "/usr/local/lib/python3.6/site-packages/rtichoke/callbacks.py", line 22, in rconsole2str
    m = UTFPATTERN.search(buf)
SystemError: Objects/moduleobject.c:449: bad argument to internal function
address 0x8, cause 'memory not mapped'

Traceback:
 1: .C("py_init", PACKAGE = "rPython")
 2: fun(libname, pkgname)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(fun(libname, pkgname), error = identity)
 7: runHook(".onLoad", env, package.lib, package)
 8: loadNamespace(package, lib.loc)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)   else stop(msg, call. = FALSE, domain = NA)})
13: library(rPython)
```

This appears to be an rtichoke issue because it works fine at the normal R prompt and inside RStudio.

- rtichoke installed in python 3.6
- rPython version 0.0.6
- R version 3.4.2 (2017-09-28) -- "Short Summer"
- Platform: x86_64-apple-darwin15.6.0 (64-bit)

**Comment by randy3k** [comment]
It is expected. rtichoke is s python program and you are trying to reinitiate the python instance. You could ask the author of rPython to address it. Another solution is to switch to [reticulate]( https://github.com/rstudio/reticulate) if `rPython` is not strictly required. However, you might need to install this [particular version](https://github.com/rstudio/reticulate/pull/279) for now.

**Comment by swt30** [comment]
Thanks for the info—rPython appears unmaintained and it turns out I don't even need it (or can use reticulate instead in the future), so will close this issue.
