### ISSUE TITLE
Can't find libRblas.so

### ISSUE THREAD

**Issue by t-kalinowski** [randy3k/rtichoke#60]
Hello, when I try to run rtichoke, I get this error:
```
Traceback (most recent call last):
  File "/home/tomasz/.local/bin/rtichoke", line 11, in <module>
    sys.exit(main())
  File "/home/tomasz/.local/lib/python2.7/site-packages/rtichoke/__init__.py", line 66, in main
    RtichokeApplication(r_home, ver=__version__).run(options)
  File "/home/tomasz/.local/lib/python2.7/site-packages/rtichoke/rtichokeapp.py", line 159, in run
    self.m = Machine(set_default_callbacks=False, verbose=options.debug)
  File "/home/tomasz/.local/lib/python2.7/site-packages/rapi/bootstrap.py", line 215, in __init__
    libR = find_libR(rhome)
  File "/home/tomasz/.local/lib/python2.7/site-packages/rapi/utils.py", line 74, in find_libR
    return PyDLL(str(libRpath), mode=RTLD_GLOBAL)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 361, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libRblas.so: cannot open shared object file: No such file or directory
```

Fedora 27, built R from source using `--with-blas` flag and all other defaults in `./configure`

**Comment by t-kalinowski** [comment]
solved it by running `env LD_LIBRARY_PATH=/usr/local/lib64/R/lib:$LD_LIBRARY_PATH rtichoke`

Is there a neater way to solve this?

**Comment by randy3k** [comment]
what version of rtichoke are you using? The latest release should contain a patch to export the variable automatically

**Comment by randy3k** [comment]
does your shell set the variable `LD_LIBRARY_PATH` already? The patch won’t work if it was set.

**Comment by t-kalinowski** [comment]
I just tried the git version, same error.

I do set the LD_LIBRARY_PATH already for other things that require it... I don't see a way out of that unfortunately.

**Comment by randy3k** [comment]
thanks, i will make a release to address it once I have a computer access (on mobile now)

**Comment by randy3k** [comment]
v0.2.6 is out.
