### ISSUE TITLE
compatability with R-devel?

### ISSUE THREAD

**Issue by sckott** [randy3k/rtichoke#70]
I don't remember having problems using `rtichoke` with R-devel, but just yesterday wanted to run something on R devel on mac-os, and rtichoke throws error:

```
➜  ~ rtichoke
Error in rbind(info, getNamespaceInfo(env, "S3methods")) :
  number of columns of matrices must match (see arg 2)
Traceback (most recent call last):
  File "/usr/local/bin/rtichoke", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/rtichoke/__init__.py", line 74, in main
    RtichokeApplication(r_home, ver=__version__).run(options)
  File "/usr/local/lib/python3.7/site-packages/rtichoke/rtichokeapp.py", line 172, in run
    namespace.register_py_namespace()
  File "/usr/local/lib/python3.7/site-packages/rapi/namespace.py", line 257, in register_py_namespace
    ["[<-", "PyObject"]
  File "/usr/local/lib/python3.7/site-packages/rapi/namespace.py", line 102, in register_s3_methods
    rcall(("base", "registerS3methods"), m, name, ns)
  File "/usr/local/lib/python3.7/site-packages/rapi/interface.py", line 218, in rcall
    return RObject(rcall_p(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/rapi/interface.py", line 208, in rcall_p
    return rexec_p(Rf_eval, rlang_p(*args, **kwargs), R_GlobalEnv)
  File "/usr/local/lib/python3.7/site-packages/rapi/interface.py", line 79, in rexec_p
    raise RuntimeError("rexec encountered an error")
RuntimeError: rexec encountered an error
```

The error happened on pypi version of rtichoke and devel 

I'm on Python 3.7.1

**Comment by randy3k** [comment]
There are some recent updates at the `registerS3methods` function. https://github.com/wch/r-source/commit/7972b2300f5bf9bde2acba52e03b61458bd33126#diff-730800c01bc3e932fee6f66d00bdc195
and that broke rtichoke.

**Comment by sckott** [comment]
nice find.

**Comment by randy3k** [comment]
the master branch will work with rdevel now. However, the reticulate repl mode will not work without the injected `.py` namespace.

**Comment by sckott** [comment]
okay, thanks for the quick fix!

**Comment by randy3k** [comment]
I will post a more complete fix soon

**Comment by randy3k** [comment]
The latest rtichoke v0.2 ships with a complete fix for R-devel.

**Comment by sckott** [comment]
awesome, thanks very much
